services:
  - type: web
    name: ai-photo-enhancer-backend
    env: python
    rootDir: backend
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: "/"
