services:
  - type: web
    name: ai-photo-enhancer-backend
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app

