services:
  - type: web
    name: ai-photo-enhancer-backend
    env: python
    plan: free
    pythonVersion: "3.11"
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
